In [2]:
import pandas as pd


df = pd.read_csv(
    r'D:\Main\projects\ML-playground-\02_Manually_creating_algorithm\01_Niave_Bayes\data.csv',
    engine='pyarrow'
)
df.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [3]:
(
    df.groupby('play')
    .agg(
        counts=('play','count')
    )
    .reset_index()
    .to_dict()
)

{'play': {0: 'No', 1: 'Yes'}, 'counts': {0: 5, 1: 9}}

In [4]:
Total_Postives = df[df['play'] == 'Yes']['play'].count()
Total_Nagtives = df[df['play'] == 'No']['play'].count()

In [5]:
df.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [6]:
df.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [7]:
for col in df.iloc[:,1:-1].columns:
    print(col)

outlook
temp
humidity
wind

In [23]:
for col in df.iloc[:,1:-1].columns:
    result = df.groupby(col).agg(
        Yes=('play', lambda x: (x == 'Yes').sum()),
        No=('play', lambda x: (x == 'No').sum())
    ).reset_index()
    result['TotalYes']=Total_Postives
    result['TotalNo']=Total_Nagtives
    result['p_Yes']=result['Yes'] / result['TotalYes']
    result['p_No']=result['No'] / result['TotalNo']
    print(result)

    outlook  Yes  No  TotalYes  TotalNo     p_Yes  p_No
0  Overcast    4   0         9        5  0.444444   0.0
1      Rain    3   2         9        5  0.333333   0.4
2     Sunny    2   3         9        5  0.222222   0.6
   temp  Yes  No  TotalYes  TotalNo     p_Yes  p_No
0  Cool    3   1         9        5  0.333333   0.2
1   Hot    2   2         9        5  0.222222   0.4
2  Mild    4   2         9        5  0.444444   0.4
  humidity  Yes  No  TotalYes  TotalNo     p_Yes  p_No
0     High    3   4         9        5  0.333333   0.8
1   Normal    6   1         9        5  0.666667   0.2
     wind  Yes  No  TotalYes  TotalNo     p_Yes  p_No
0  Strong    3   3         9        5  0.333333   0.6
1    Weak    6   2         9        5  0.666667   0.4

In [9]:
result = df.groupby('outlook').agg(
    Yes=('play', lambda x: (x == 'Yes').sum()),
    No=('play', lambda x: (x == 'No').sum())
).reset_index()
result['TotalYes']=Total_Postives
result['TotalNo']=Total_Nagtives
result['p_Yes']=result['Yes'] / result['TotalYes']
result['p_No']=result['No'] / result['TotalNo']
result

    outlook  Yes  No  TotalYes  TotalNo     p_Yes  p_No
0  Overcast    4   0         9        5  0.444444   0.0
1      Rain    3   2         9        5  0.333333   0.4
2     Sunny    2   3         9        5  0.222222   0.6

In [13]:
result = (
    df.groupby('play')
    .agg(
        count=('play','count')
    )
    .reset_index()
)
result

  play  count
0   No      5
1  Yes      9

In [20]:
y = df['play']

In [21]:
y.value_counts().to_dict()

{'Yes': 9, 'No': 5}